#!/bin/bash
GIT="/usr/bin/git"

# backup dwm setup
DWM_DIR="$HOME/.dwm-setup"
cd $DWM_DIR || exit
if [[ -n "$($GIT status -b --porcelain)" ]]; then
  git add . >/dev/null
  git commit -m "Automated update: $(date --rfc-3339 s)" >/dev/null
  git push >/dev/null
fi

# backup dotfiles
DOTFILES_DIR="$HOME/.dotfiles"
cd $DOTFILES_DIR || exit
if [[ -n "$($GIT status -b --porcelain)" ]]; then
  git add . >/dev/null
  git commit -m "Automated update: $(date --rfc-3339 s)" >/dev/null
  git push >/dev/null
fi
